dataset_path: 
  train: /cmnfs/data/proteomics/shabaz_exotic/processed/parquet/allinone/*train*.parquet
  val: /cmnfs/data/proteomics/shabaz_exotic/processed/parquet/allinone/*val*parquet
  test: /cmnfs/data/proteomics/shabaz_exotic/processed/parquet/allinone/*test*parquet
tokenizer: mine
sequence_dictionary_path: /cmnfs/data/proteomics/shabaz_exotic/processed/merged_search/allinone/token_dictionary.txt
ion_counts_path: /cmnfs/data/proteomics/shabaz_exotic/processed/merged_search/allinone/ion_counts.tab
method_list: [ECD,EID,UVPD,HCD]
pep_length: [6, 30]
charge: [1, 6]
batch_size: 100
num_workers: 8
buffer_size: 10000

