running_units: 256
penult_units: 512
d: 64
h: 8
ffn_mult: 1
dropout: 0
num_methods: 4
alphabet: False
rotation_matrix: False
prenorm: False
norm_type: 'layer'
depth: 6
prec_type: 'preembed' # preembed | pretoken
prec_units: 256
use_charge: True
use_energy: False
use_method: True
final_act: 'sigmoid' # sigmoid | identity | linear
